name: notes
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  go_router: ^14.3.0
  path_provider: ^2.1.5
  intl: any
  intl_utils: ^2.8.7
  hive_ce: ^2.7.0
  hive_ce_flutter: ^2.1.0
  rxdart: ^0.27.7
  gap: ^3.0.1
  shimmer: ^3.0.0
  formz: ^0.8.0 
  toastification: ^2.3.0
  mockito: ^5.4.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  hive_ce_generator: ^1.7.0

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  class_name: AppText
  arb_dir: lib/core/localizations
  output_dir: lib/core/localizations/generated